import json
import os

print("Building integrated web portal script...")

# 1. Load site_metric_data_7dates.json
with open('site_metric_data_7dates.json', 'r', encoding='utf-8') as f:
    site_metric_data = json.load(f)

# 2. Define Site Encyclopedia Data (Enhanced with Negative Ions, 7th survey stats, Asphalt note, and CLHEI)
site_encyclopedia_data = [
    {
        "no": 1,
        "name": "리기다소나무림",
        "latin": "Pinus rigida Mill.",
        "category": "conifer",
        "catName": "온대 침엽수림 (인공 조림)",
        "location": "학술림 하단 완경사 산록부 (해발 210m)",
        "soilPh": "pH 6.1",
        "soilMoist": "32.5%",
        "tafMean": 561.0,
        "tabMean": 14.0,
        "nIonMean": 1377.0,
        "clhei": 82.3,
        "grade": "2등급 (우수 생태 건강림)",
        "peak": "4월 봄철 (688 CFU/㎥)",
        "summerTaf": 496.0,
        "springDna": [{"g": "Capnodiales_sp.", "pct": 36.6}, {"g": "Penicillium", "pct": 25.1}, {"g": "Nectriaceae", "pct": 10.4}, {"g": "Cladosporium", "pct": 10.1}],
        "summerDna": [{"g": "Trichoderma", "pct": 99.9}, {"g": "Penicillium", "pct": 0.1}],
        "microbeTraits": "송진(테르펜) 함유 솔잎 낙엽층의 완만한 분해 특성. 여름철 고온다습기에 Trichoderma가 99.9%로 단일 극우점하여 토양 유기물 분해를 독점.",
        "plantMicrobe": "척박지 녹화 수종으로 도입된 리기다소나무는 두터운 송진 함유 침엽수 낙엽 매트층을 형성하며, 산성 토양에 적응한 자낭균류 피생균 및 목재부후균과 서식처를 공유함.",
        "nutrientCycling": "바늘잎의 두꺼운 왁스/큐티클층으로 인해 분해 속도가 완만하며, 7월 장마기 토양 고습 조건에서 Trichoderma에 의한 셀룰로오스 초고속 가수분해가 집중적으로 발생.",
        "bioindicator": "자연 토양 유익균의 생물방제(Biocontrol) 길항 미생물상 구축 지표이자, 외부 인위적 오염이 없는 건전한 산림 임분 지표.",
        "healthGuide": "솔잎 테르펜 피톤치드 효과와 안정적인 음이온(1,377 개/cm³) 방출. 4월 건조 강풍기에는 엽면 부유 포자가 다소 증가하므로 알레르기 민감군은 마스크 착용 권장."
    },
    {
        "no": 2,
        "name": "잣나무림 a",
        "latin": "Pinus koraiensis Siebold & Zucc. (Stand A)",
        "category": "conifer",
        "catName": "온대 침엽수림 (울창한 계곡 임분)",
        "location": "계곡 인접 완경사지, 수관 울폐도 85% 이상 (해발 235m)",
        "soilPh": "pH 6.3",
        "soilMoist": "37.8%",
        "tafMean": 893.7,
        "tabMean": 36.3,
        "nIonMean": 1820.5,
        "clhei": 79.8,
        "grade": "2등급 (우수 생태 건강림)",
        "peak": "7월 한여름 (2,104 CFU/㎥, 전 지점 2위)",
        "summerTaf": 2104.0,
        "springDna": [{"g": "Cladosporium", "pct": 41.3}, {"g": "Capnodiales", "pct": 27.9}, {"g": "Alternaria", "pct": 21.9}],
        "summerDna": [{"g": "Trichoderma", "pct": 75.0}, {"g": "Bjerkandera", "pct": 13.7}, {"g": "Penicillium", "pct": 7.1}, {"g": "Coprinellus", "pct": 1.0}],
        "microbeTraits": "봄철 4대 알레르겐(Cladosporium, Alternaria 등 63.2%) 우점에서 여름철 고온다습기 Trichoderma(75%) 및 목재부후균 Bjerkandera(13.7%)로의 극적 천이.",
        "plantMicrobe": "잣나무 밀식 수관이 직사광선을 차단하고 바닥 낙엽층의 습도를 상시 보존하여 낙엽층 부식이 왕성하게 진행됨.",
        "nutrientCycling": "여름철 다우기 직후(강우 64.6mm) 토양 셀룰로오스 분해균과 버섯 균사가 대량 번식하여 산림 생태계 양분 순환을 가속.",
        "bioindicator": "수관 울폐도 극대화에 따른 하층 고습도 유지 지표종 및 산림 부식토 형성 지표.",
        "healthGuide": "여름철 다습기에는 포자 밀도가 2,000 CFU/㎥를 초과하므로, 중증 천식 환자는 다우 직후 체류를 자제하고 통풍이 원활한 능선부(Site 10) 이용 권장."
    },
    {
        "no": 3,
        "name": "버들나무림 a (왕버들 a)",
        "latin": "Salix koreensis Andersson (Stand A)",
        "category": "riparian",
        "catName": "수변 저습지 활엽수림",
        "location": "계곡 수변부 및 저습지, 상시 물안개 (해발 190m)",
        "soilPh": "pH 6.5",
        "soilMoist": "42.1% (최고)",
        "tafMean": 1087.8,
        "tabMean": 26.7,
        "nIonMean": 1580.4,
        "clhei": 78.2,
        "grade": "2등급 (우수 생태 건강림)",
        "peak": "7월 한여름 (1,672 CFU/㎥), 8월 (1,452 CFU/㎥)",
        "summerTaf": 1672.0,
        "springDna": [{"g": "Capnodiales", "pct": 50.1}, {"g": "Cladosporium", "pct": 29.2}, {"g": "Septotinia", "pct": 3.2}, {"g": "Fusarium", "pct": 3.1}],
        "summerDna": [{"g": "Trichoderma", "pct": 78.0}, {"g": "Fusarium", "pct": 10.2}, {"g": "Coprinellus", "pct": 3.1}, {"g": "Clonostachys", "pct": 2.9}],
        "microbeTraits": "연중 700~1,670 CFU/㎥의 지속적 고농도 유지. 수변 고습 환경과 활엽수 엽면 조직 특이적 수목 병원성 및 부생 사상균 우점.",
        "plantMicrobe": "하천 변 수분 포화 토양과 활엽수 연약 잎 조직으로 인해 분해 및 병원성 진균의 활성이 연중 지속됨. 수변 완충 식생의 수질 정화 및 미기후 습도 유지 기능.",
        "nutrientCycling": "활엽수 낙엽은 침엽수에 비해 분해 속도가 빠르며 수변 미생물 군집에 의해 유기탄소가 수계와 대기로 활발히 순환.",
        "bioindicator": "수변 저습지 미기후 및 활엽수 잎 탄저병·잎마름병 조기 경보 지표 구역.",
        "healthGuide": "수변 레너드 효과로 풍부한 음이온(1,580 개/cm³)이 생성되나 곰팡이 과민성 비염 환자는 여름철 장시간 체류 시 비염 악화 가능성 유의."
    },
    {
        "no": 4,
        "name": "밭 (개활 경작지 대조구)",
        "latin": "Agricultural Cultivated Field (Control)",
        "category": "control",
        "catName": "인위적 개활 경작지 (양성 대조구)",
        "location": "학술림 진입부 경작지, 수관 0% 완전 개활 (해발 180m)",
        "soilPh": "pH 6.8",
        "soilMoist": "31.0%",
        "tafMean": 1217.7,
        "tabMean": 144.3,
        "nIonMean": 566.6,
        "clhei": 71.3,
        "grade": "3등급 (보통 생태 녹지)",
        "peak": "7월 한여름 (2,464 CFU/㎥, 전 지점 최고)",
        "summerTaf": 2464.0,
        "springDna": [{"g": "봄철 미포집 (하절기 집중)", "pct": 0.0}],
        "summerDna": [{"g": "Fusarium", "pct": 45.1}, {"g": "Penicillium", "pct": 32.5}, {"g": "Aspergillus", "pct": 10.4}, {"g": "Nectriaceae", "pct": 7.6}],
        "microbeTraits": "토양 서식 식물 시들음병균인 Fusarium oxysporum(45.1%)과 저장 사상균 Penicillium/Aspergillus(42.9%)가 지표면 비산 먼지와 함께 대량 방출.",
        "plantMicrobe": "수관 부재로 강우와 직사광선이 나지에 직접 도달하며, 작물 시비 유기물과 토양 교란이 사상균의 폭발적 비산을 유발.",
        "nutrientCycling": "인공적 영농 활동에 의한 빠른 유기물 턴오버와 건조기 토양 미세먼지(PM10) 동반 비산.",
        "bioindicator": "인위적 지표면 교란 및 영농성 먼지 비산 지표 구역.",
        "healthGuide": "Fusarium의 곰팡이독소(Fumonisin, T-2) 및 미세 분진 흡입 위험이 있으며, 음이온이 산림의 40% 수준으로 저조하여 마스크 착용 권장."
    },
    {
        "no": 5,
        "name": "주차장 (인공 포장 대조구)",
        "latin": "Paved Asphalt Parking Lot Control",
        "category": "control",
        "catName": "불투수 아스팔트 포장면 (음성 대조군)",
        "location": "관리사무소 앞 아스팔트 포장면, 식생 부재 (해발 185m)",
        "soilPh": "측정불가 (NaN - 아스팔트)",
        "soilMoist": "측정불가 (NaN - 아스팔트)",
        "tafMean": 363.9,
        "tabMean": 20.3,
        "nIonMean": 1235.0,
        "clhei": 83.1,
        "grade": "2등급 (우수 생태 건강림)",
        "peak": "4월 (456 CFU/㎥), 7월 (326 CFU/㎥)",
        "summerTaf": 326.0,
        "springDna": [{"g": "봄철 미포집 (하절기 집중)", "pct": 0.0}],
        "summerDna": [{"g": "Fusarium", "pct": 33.4}, {"g": "Coprinellus", "pct": 29.8}, {"g": "Nectriaceae", "pct": 18.3}, {"g": "Penicillium", "pct": 13.4}],
        "microbeTraits": "연중 평균 363.9 CFU/㎥로 10개 지점 중 최저치. 전 조사 기간 동안 환경부 실내 권고기준(500 CFU/㎥)을 상시 만족하는 유일한 지점.",
        "plantMicrobe": "수목 및 낙엽층 부재 시 자연계 진균 포자 방출원이 형성되지 않음을 역설적으로 입증하는 '음성 대조군(Negative Control)'.",
        "nutrientCycling": "불투수 아스팔트 포장층으로 자연 토양 순환 차단됨. 토양 온습도/pH는 물리적으로 측정 불가하여 결측치(NaN)로 공식 보정 처리됨.",
        "bioindicator": "비산란성 인공 피복면 및 광역 대기 배경농도 지표.",
        "healthGuide": "진균 포자는 적으나 아스팔트 복사열 및 차량 배기가스가 존재하므로 산림 치유 목적으로 머무르는 공간은 아님."
    },
    {
        "no": 6,
        "name": "소나무림",
        "latin": "Pinus densiflora Siebold & Zucc.",
        "category": "conifer",
        "catName": "온대 천연 침엽수림",
        "location": "중턱 능선 사면 온대 자연림, 풍부한 간벌 고사목 (해발 280m)",
        "soilPh": "pH 5.9",
        "soilMoist": "28.4%",
        "tafMean": 539.0,
        "tabMean": 172.3,
        "nIonMean": 2196.7,
        "clhei": 81.4,
        "grade": "2등급 (우수 생태 건강림)",
        "peak": "7월 (750 CFU/㎥), 8월 (746 CFU/㎥)",
        "summerTaf": 750.0,
        "springDna": [{"g": "Capnodiales", "pct": 28.2}, {"g": "Penicillium", "pct": 17.5}, {"g": "Cladosporium", "pct": 16.3}, {"g": "Umbelopsis", "pct": 16.2}],
        "summerDna": [{"g": "Coprinellus", "pct": 59.4}, {"g": "Irpex", "pct": 11.8}, {"g": "Capnodiales", "pct": 9.6}, {"g": "Trichoderma", "pct": 8.9}],
        "microbeTraits": "여름철 담자균문 백색부후균 Coprinellus radians(방사형먹물버섯류, 59.4%)와 Irpex laceratus(11.8%)가 71.2%를 합작 독점.",
        "plantMicrobe": "소나무 고사목과 간벌재 리그닌을 분해하여 난분해성 유기물을 토양 부식토로 전환시키는 탄소 순환의 핵심 현장.",
        "nutrientCycling": "복합 리그닌 고분자 물질을 Laccase 및 Peroxidase 효소로 분해하여 산림 토양 유기물 층을 재생.",
        "bioindicator": "자연 온대 소나무림의 성숙도 및 고사목 축적 상태 지표.",
        "healthGuide": "음이온 발생량 2,196.7 개/cm³(밭의 2.35배)과 강력한 피톤치드 방출로 **학술림 최고의 산림욕 힐링 구역**. 버섯 포자 알레르기 유증상자는 다우 직후 방문 시 마스크 착용 권장."
    },
    {
        "no": 7,
        "name": "일본잎갈나무림 a (낙엽송 a)",
        "latin": "Larix kaempferi (Stand A)",
        "category": "conifer",
        "catName": "낙엽성 침엽수 인공림",
        "location": "남동사면 완경사지, 일조 투과 및 통풍 우수 (해발 250m)",
        "soilPh": "pH 6.2",
        "soilMoist": "31.2%",
        "tafMean": 444.3,
        "tabMean": 34.0,
        "nIonMean": 2965.5,
        "clhei": 80.9,
        "grade": "2등급 (우수 생태 건강림)",
        "peak": "5월 초여름 (868 CFU/㎥), 7월 (640 CFU/㎥)",
        "summerTaf": 640.0,
        "springDna": [{"g": "Capnodiales", "pct": 63.7}, {"g": "Alternaria", "pct": 13.7}, {"g": "Cladosporium", "pct": 11.1}],
        "summerDna": [{"g": "Cladosporium", "pct": 24.4}, {"g": "Capnodiales", "pct": 23.2}, {"g": "Trichoderma", "pct": 22.8}, {"g": "Penicillium", "pct": 12.2}],
        "microbeTraits": "연중 평균 444 CFU/㎥로 전체 산림 임분 중 가장 청정. 특정 종의 독점 없이 Capnodiales, Cladosporium, Trichoderma가 균형을 이룸.",
        "plantMicrobe": "낙엽송 특유의 광 투과성과 우수한 공기 유동성으로 인해 임내 습도 정체가 발생하지 않음. 안정적 낙엽 분해와 청정한 수관 환경 형성.",
        "nutrientCycling": "매년 늦가을 발생하는 다량의 낙엽이 봄철 신엽 전개기와 함께 점진적으로 분해되어 토양 영양분 환원.",
        "bioindicator": "쾌적하고 건전한 온대 침엽수 인공림 대기질 지표.",
        "healthGuide": "음이온 실측치 **2,965.5 개/cm³(밭 대비 3.17배, 전 지점 1위)** 및 대기질 최청정 구간으로 **학술림 내 최우수 산림 치유 산책 코스로 적극 추천**."
    },
    {
        "no": 8,
        "name": "버들나무림 b (왕버들 b)",
        "latin": "Salix koreensis (Stand B)",
        "category": "riparian",
        "catName": "수변 계곡 하류 활엽수림",
        "location": "계곡 하류 퇴적지, 고수위 및 퇴적 유기물 풍부 (해발 185m)",
        "soilPh": "pH 6.4",
        "soilMoist": "40.8%",
        "tafMean": 1214.0,
        "tabMean": 24.3,
        "nIonMean": 1461.2,
        "clhei": 76.7,
        "grade": "2등급 (우수 생태 건강림)",
        "peak": "4월 봄철 (1,658 CFU/㎥, 봄철 전 지점 1위)",
        "summerTaf": 1298.0,
        "springDna": [{"g": "Capnodiales", "pct": 71.0}, {"g": "Alternaria", "pct": 13.0}, {"g": "Coprinellus", "pct": 3.3}],
        "summerDna": [{"g": "Trichoderma", "pct": 29.7}, {"g": "Fusarium", "pct": 27.0}, {"g": "Colletotrichum", "pct": 24.2}, {"g": "Alternaria", "pct": 4.5}],
        "microbeTraits": "봄철 신엽 개엽기 Cladosporium/Capnodiales 조기 대량 비산(1,658) 및 여름철 활엽수 탄저병균 Colletotrichum(24.2%)의 집중 발생.",
        "plantMicrobe": "계곡 상류로부터 운반된 유기물 집적과 높은 습도로 인해 수변 미생물 대사 활성이 극대화됨. 왕버들 탄저병 발생 모니터링의 핵심 지표.",
        "nutrientCycling": "수생 생태계와 육상 생태계 간의 전이대(Ecotone) 물질 교환 및 고속 질소/인 순환.",
        "bioindicator": "수변 활엽수림 탄저병(Anthracnose) 병해 조기 경보 지표.",
        "healthGuide": "4월에 1급 알레르겐 포자 농도가 높으므로 알레르기 비염 및 천식 환자는 봄철 진입 시 주의 필요. 수변 계곡의 청량감은 우수함."
    },
    {
        "no": 9,
        "name": "일본잎갈나무림 b (낙엽송 b)",
        "latin": "Larix kaempferi (Stand B)",
        "category": "conifer",
        "catName": "경사지 낙엽송 임분",
        "location": "사면 상단부 능선 바람받이 사면 (해발 310m)",
        "soilPh": "pH 6.0",
        "soilMoist": "29.5%",
        "tafMean": 930.0,
        "tabMean": 357.7,
        "nIonMean": 1150.0,
        "clhei": 74.4,
        "grade": "2등급 (우수 생태 건강림)",
        "peak": "4월 봄철 (1,146 CFU/㎥, 세균 1,954 CFU/㎥)",
        "summerTaf": 472.0,
        "springDna": [{"g": "Capnodiales", "pct": 49.2}, {"g": "Fusarium", "pct": 24.6}, {"g": "Clonostachys", "pct": 11.2}, {"g": "Alternaria", "pct": 9.5}],
        "summerDna": [{"g": "Aspergillus", "pct": 30.9}, {"g": "Fusarium", "pct": 25.4}, {"g": "Trichoderma", "pct": 17.4}, {"g": "Ceriporia", "pct": 9.5}],
        "microbeTraits": "4월 건조 강풍(최대 16.3m/s) 시 엽면 피생균(Capnodiales 49%) 및 토양 세균(1,954)의 일시적 풍식 비산. 여름철 목재부후균 Ceriporia(9.5%) 출현.",
        "plantMicrobe": "바람받이 사면의 물리적 미기후 역학을 반영하며, 계절 간 기상 변동에 민감하게 반응하는 산림 대기 완충 지표 임분.",
        "nutrientCycling": "강풍에 의한 수관 포자 확산과 토양 표면 건조화에 따른 간헐적 분해 활성.",
        "bioindicator": "바람받이 사면의 물리적 풍식 및 기상 민감도 지표.",
        "healthGuide": "봄철 강풍 시 일시적으로 미세 입자 비산이 많으므로 방풍 안경 및 마스크 착용이 유리함. 통풍이 좋아 여름철에는 쾌적함."
    },
    {
        "no": 10,
        "name": "잣나무림 b",
        "latin": "Pinus koraiensis (Stand B)",
        "category": "conifer",
        "catName": "능선 연접 잣나무림",
        "location": "상부 능선부 연접 사면, 통풍 양호 (해발 350m)",
        "soilPh": "pH 6.1",
        "soilMoist": "33.4%",
        "tafMean": 520.7,
        "tabMean": 23.7,
        "nIonMean": 1690.0,
        "clhei": 77.0,
        "grade": "2등급 (우수 생태 건강림)",
        "peak": "8월 늦여름 (912 CFU/㎥), 7월 (638 CFU/㎥)",
        "summerTaf": 638.0,
        "springDna": [{"g": "Penicillium", "pct": 50.1}, {"g": "Capnodiales", "pct": 32.1}, {"g": "Coprinellus", "pct": 15.1}],
        "summerDna": [{"g": "Trichoderma", "pct": 80.2}, {"g": "Aspergillus", "pct": 9.7}, {"g": "Bjerkandera", "pct": 8.5}, {"g": "Oudemansiella", "pct": 1.1}],
        "microbeTraits": "봄철 Penicillium mallochii(50.1%) 우점에서 여름철 Trichoderma(80.2%)로의 전환. 계곡부 Stand A 대비 진균 농도가 절반 이하로 안정적 억제.",
        "plantMicrobe": "동일 잣나무 수종임에도 능선 지형의 우수한 통풍성으로 인해 습도 정체가 해소되어 진균 농도가 크게 낮아짐. '지형 미기후 조절 메커니즘'의 증거.",
        "nutrientCycling": "통풍 사면의 규칙적인 건습 반복으로 균일하고 위생적인 낙엽 부식토 형성.",
        "bioindicator": "능선부 미기후에 의한 포자 농도 완충 지표.",
        "healthGuide": "잣나무 피톤치드 치유 효과를 누리면서도 고습도 곰팡이 포자를 회피할 수 있는 최적의 힐링 코스."
    }
]

# 3. Define 31 figures metadata
figures_data = [
    # DNA NGS Figures
    {"id": "dna-fig1", "cat": "dna", "title": "Fig 1. 계절별 공기진균 알파 다양성 (Shannon, Chao1)", "src": "images/fig1_seasonal_alpha_diversity.png", "desc": "봄철 대비 여름철 생물다양성 지수(Shannon H', Richness Chao1)의 계절적 상승 및 군집 풍부도 변화 구명"},
    {"id": "dna-fig2", "cat": "dna", "title": "Fig 2. 문(Phylum) 및 강(Class) 계절별 군집 조성비", "src": "images/fig2_phylum_class_composition.png", "desc": "자낭균문(Ascomycota) 및 담자균문(Basidiomycota)의 봄-여름 비율 교체 및 Dothideomycetes, Sordariomycetes 천이"},
    {"id": "dna-fig3", "cat": "dna", "title": "Fig 3. 10대 조사지점별 상위 속(Top Genera) 히트맵", "src": "images/fig3_top_genera_heatmap.png", "desc": "Capnodiales, Cladosporium, Trichoderma, Fusarium 등 상위 25대 주요 속의 지점별·시기별 상대 풍부도"},
    {"id": "dna-fig4", "cat": "dna", "title": "Fig 4. 베타 다양성 PCoA (Bray-Curtis 거리)", "src": "images/fig4_beta_diversity_pcoa.png", "desc": "봄철 vs 여름철 간의 뚜렷한 군집 구조 분리(PERMANOVA p<0.001) 및 임상별 군집 이질성 검증"},
    {"id": "dna-fig5", "cat": "dna", "title": "Fig 5. 기능군(Functional Guilds) 및 호흡기 알레르겐", "src": "images/fig5_functional_guilds_allergens.png", "desc": "FUNGuild 기반 부생균, 식물병원균, 공생균 비율 및 Cladosporium/Alternaria 알레르겐 계절 위험도"},
    {"id": "dna-fig6", "cat": "dna", "title": "Fig 6. 공기생 상호작용 공존 네트워크 (Co-occurrence)", "src": "images/fig6_cooccurrence_network.png", "desc": "공기 미생물 군집의 모듈성 구조 및 핵심 매개 허브 분류군(Keystone Taxa: Irpex, Ceriporia) 구명"},
    {"id": "dna-fig7", "cat": "dna", "title": "Fig 7. 미생물-환경인자 상관관계 히트맵 (초기)", "src": "images/fig7_microbe_environment_correlation.png", "desc": "기온, 습도, 풍속, 토양 환경과 우점 분류군 간의 초기 2변량 피어슨 상관행렬"},
    {"id": "dna-fig8", "cat": "dna", "title": "Fig 8. 10대 지점별 배양 농도 및 실내 기준치 비교", "src": "images/fig8_bioaerosol_concentration.png", "desc": "환경부 실내공기질 권고기준(세균 800, 진균 500) 대비 10개 지점의 배양 농도 청정도 비교"},
    {"id": "dna-fig9", "cat": "dna", "title": "Fig 9. 시계열 장기 추세 및 계절 동태", "src": "images/fig9_all6dates_longitudinal_trends.png", "desc": "초봄부터 늦여름까지의 총부유세균(TAB) 및 진균(TAF) 시계열 농도 궤적"},
    {"id": "dna-fig10", "cat": "dna", "title": "Fig 10. 시공간 농도 히트맵", "src": "images/fig10_all6dates_spatiotemporal_heatmap.png", "desc": "10대 지점과 조사 차수 간의 바이오에어로졸 농도 매트릭스"},
    {"id": "dna-fig11", "cat": "dna", "title": "Fig 11. 전 조사 환경 요인 다변량 상관분석", "src": "images/fig11_all6dates_environmental_correlations.png", "desc": "기상청 종관 AWS 기상과 임내 미기후 요인의 종합 상관성"},
    {"id": "dna-fig12", "cat": "dna", "title": "Fig 12. DNA 메타게놈-거시 농도 통합 연계 모델", "src": "images/fig12_dna_macro_integration.png", "desc": "배양 농도(CFU/㎥)와 차세대 메타게놈 NGS 리드 수 간의 절대 정량화 통합 모델"},

    # Negative Ions & Climate/Eco-Health Figures
    {"id": "ion-fig01", "cat": "ion", "title": "Fig 01. 조사일자별·지점별 음이온 발생량 비교", "src": "images/01_일자별_지점별_음이온발생량_비교.png", "desc": "5대 음이온 측정 조사 시기별 10개 지점의 실측 발생량 프로파일"},
    {"id": "ion-fig02", "cat": "ion", "title": "Fig 02. 수종별 음이온 계절 추세 변화", "src": "images/02_수종별_계절추세_변화.png", "desc": "낙엽송, 소나무, 잣나무, 활엽수림의 봄-가을 음이온 상승 궤적"},
    {"id": "ion-fig03", "cat": "ion", "title": "Fig 03. 산림(8개소) vs 대조구 음이온 배율 비교", "src": "images/03_산림_대조구_비교_및_배율.png", "desc": "밭 대조구(934.6) 대비 산림(1,673.1, 1.79배) 및 낙엽송(2,965.5, 3.17배) 음이온 배율"},
    {"id": "ion-fig04", "cat": "ion", "title": "Fig 04. 10대 지점별 음이온 농도 분포 박스플롯", "src": "images/04_지점별_음이온분포_박스플롯.png", "desc": "44,996건 초당 계측 빅데이터의 지점별 분산 및 중앙값 박스플롯"},
    {"id": "ion-fig05", "cat": "ion", "title": "Fig 05. 측정 시각 및 오전·오후 역순교차 안정성", "src": "images/05_측정시각_및_역순교차_비교.png", "desc": "일주기 일조 및 기온 변화에 따른 음이온 측정 편향 배제 및 일관성 검증"},
    {"id": "ion-fig06", "cat": "ion", "title": "Fig 06. 15분 세션 내 1분 단위 농도 안정성 추세", "src": "images/06_15분_세션내_1분단위_안정성추세.png", "desc": "각 조사 지점별 15분 연속 측정 세션 내 시계열 안정성 검증"},
    {"id": "ion-fig07", "cat": "ion", "title": "Fig 07. 지점별 음이온 변동계수(CV) 안정성 비교", "src": "images/07_지점별_변동계수_안정성비교.png", "desc": "수관 울폐도 및 임내 통풍에 따른 음이온 농도의 변동계수 정량 평가"},
    {"id": "ion-fig08", "cat": "ion", "title": "Fig 08. 산림 vs 대조구 미생물 억제 & 음이온 배율", "src": "images/08_산림_대조구_미생물_음이온_비교.png", "desc": "세균 52.0% 억제 및 음이온 1.79배~3.17배 증폭의 복합 치유 메커니즘"},
    {"id": "ion-fig09", "cat": "ion", "title": "Fig 09. 주요 수종별 미생물 농도 및 음이온 프로파일", "src": "images/09_수종별_미생물농도_및_음이온_프로파일.png", "desc": "수종 그룹별 세균·진균 배양 농도 및 음이온 다차원 레이더/바 프로파일"},
    {"id": "ion-fig10", "cat": "ion", "title": "Fig 10. 음이온·미생물·환경 상관관계 히트맵 (아스팔트 보정)", "src": "images/10_음이온_미생물_환경요인_상관관계_히트맵.png", "desc": "주차장 아스팔트 결측 보정 후 자연 토양(315건) Pairwise deletion 상관분석 히트맵"},
    {"id": "ion-fig11", "cat": "ion", "title": "Fig 11. 음이온-미생물-미기후 다변량 산점도 및 선형 회귀", "src": "images/11_음이온_미생물_산점도_및_회귀선.png", "desc": "상대습도, 기온, 토양수분과 음이온 농도 간의 회귀 모델 및 결정계수"},
    {"id": "ion-fig12", "cat": "ion", "title": "Fig 12. 공기미생물 7개 시기 계절 변화 추세선", "src": "images/12_공기미생물_6개시기_계절변화_추세.png", "desc": "260910 포함 7개 전 조사 시기의 세균 및 진균 계절 변화 궤적"},
    {"id": "ion-fig13", "cat": "ion", "title": "Fig 13. 임상별(침엽수 vs 활엽수) 세균·진균 박스플롯", "src": "images/13_임상별_세균_진균_분포_박스플롯.png", "desc": "침엽수림, 활엽수림, 밭, 주차장 간의 바이오에어로졸 농도 유의차 검정"},
    {"id": "ion-fig14", "cat": "ion", "title": "Fig 14. 산림 vs 밭 대조구 전 시기 미생물 농도 격차", "src": "images/14_산림_vs_밭대조구_6개시기_미생물비교.png", "desc": "영농성 교란지 대비 자연 산림의 바이오에어로졸 억제 완충 효과"},
    {"id": "ion-fig15", "cat": "ion", "title": "Fig 15. 국내외 선행연구 문헌 비교 및 벤치마킹", "src": "images/15_선행연구_비교_벤치마크_차트.png", "desc": "국내외 산림 치유림 및 도시 대기질 선행 문헌과의 비교 벤치마킹"},
    {"id": "ion-fig16", "cat": "ion", "title": "Fig 16. 기상청 불정면 AWS 대비 괴산연습림 기상 완충 효과", "src": "images/16_괴산연습림_기상완충효과.png", "desc": "종관 기상 대비 여름철 -2.1℃ 폭염 냉각 및 풍속 38.5% 감쇄 효과 입증"},
    {"id": "ion-fig17", "cat": "clhei", "title": "Fig 17. 기후생명건강지수(CLHEI) 수종별 레이더 차트", "src": "images/17_기후생명건강지수_수종별_비교_레이더차트.png", "desc": "BSI(생체안락도), NVI(천연활력도), API(대기청정도), MBI(미생물건전도) 수종별 4대 축 비교"},
    {"id": "ion-fig18", "cat": "clhei", "title": "Fig 18. 기후생명건강지수(CLHEI) 7개 시기 계절 추세선", "src": "images/18_기후생명건강지수_6개시기_계절추세.png", "desc": "초봄부터 가을까지의 산림 vs 대조구 생태지수 계절 동태"},
    {"id": "ion-fig19", "cat": "clhei", "title": "Fig 19. 산림 vs 밭 대조구 생태지수(CLHEI) 격차 분석", "src": "images/19_산림_vs_밭대조구_생태지수_격차분석.png", "desc": "자연 산림(85.8점 1등급)과 경작지(62.4점 3등급) 간의 23.4점 격차 실증"}
]

print(f"Total figures defined: {len(figures_data)}")

# Serialize for JavaScript embedding
site_metric_data_json = json.dumps(site_metric_data, ensure_ascii=False)
site_encyclopedia_data_json = json.dumps(site_encyclopedia_data, ensure_ascii=False)
figures_data_json = json.dumps(figures_data, ensure_ascii=False)

print("Data serialization complete.")
